version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672
  seq:
    image: "datalust/seq:latest"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 4444:80
  controlplane:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5001:5001
  notifications:
    build:
      context: .
      dockerfile: Dockerfile.notifications
    ports:
      - 5000:5000
