version: "3"
services:
  foo:
    image: "rabbitmq:3-management"

    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
