name: Gadget

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet build Gadget.Inspector
      - run: dotnet build Gadget.Server
